### ISSUE TITLE
Optimize import process 

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ZoteroImport#12]
To avoid memory allocation issues we're simply raising the memory limit using `ini_set('memory_limit','500M')`) at the beginning of the import process. We should consider ways to optimize the process so we don't have to rely on changing configuration at runtime.

One thing we could do is not build the Zotero parent and child item arrays in their entirety before batch creating the Omeka items. Instead we could find a way to request Zotero parent items, retrieve their children in a separate request, and create the Omeka items all within one batch iteration. Doing this should minimize overhead.

We discovered a memory leak when batch creating ZoteroImportItems where associated items are being managed and not detached. Detaching items there, by adding a `cascade={"detach"}` to the ManyToOne entity annotation, or calling `$em->clear('Omeka\Entity\Resource')` at the end of every iteration, should help.

**Comment by zerocrates** [comment]
An option for reducing upfront memory usage
- Use the items/top endpoint to get just "real" top-level items, import them as they come in, page by page (so, don't keep the actual item data around). Keep only a mapping from Item ID to Zotero ID for each imported item.
- Use the items endpoint with itemType=attachment to get only the attachments. For these, page through them the same way as the items, attaching them to their appropriate parent by looking up the ID in the Omeka Item ID to Zotero ID mapping you created before

This should be an improvement over just issuing many individual-item requests to get each attachment, as it results in fewer requests to the API, and keeps closer to the structure of how the importer works now. Instead of keeping all the metadata for every item and attachment around to begin with before importing starts, you can import as you go, and you need only keep a very small array mapping the IDs to each other. As a side benefit this should result in automatically skipping the notes as well.

**Comment by jimsafley** [comment]
For the second bullet point, do you mean I should perform an API update for every attachment assigned to an previously created item?

**Comment by zerocrates** [comment]
Media have their own adapter so I would think you could do a batchCreate of them, that's what I was thinking there.

**Comment by jimsafley** [comment]
A change to core patched most of the memory leak https://github.com/omeka/omeka-s/commit/58b7861c121f13295f65223aac73c86a7b3a181d I think this, alongside the changes in dfc6008, satisfies most concerns about reaching the memory limit.

Keeping this issue open in case we want to further optimize the import logic as explained in https://github.com/omeka-s-modules/ZoteroImport/issues/12#issuecomment-261081165

**Comment by jimsafley** [comment]
One unfortunate side effect of changing import logic is if the job is stopped during batch item create, no media will be included, since media creation happens afterwards. This means the user will need to undo the import. Using the "Added after" field to start up another import where the stopped one left off is no longer an option.
