### ISSUE TITLE
Undo import button placement got wonky

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/ZoteroImport#18]
Probably a result of core CSS changes, the placement for the undo button no longer aligns. (Looks similar to the odd placement of action buttons for resource templates)

![zoteroimportundobutton](https://user-images.githubusercontent.com/153262/29722660-af5d9114-898f-11e7-98d6-669bd733e0a8.png)

**Comment by patrickmj** [comment]
I don't see a handy way to fix this. @kimisgold, any ideas ?

**Comment by kimisgold** [comment]
The inline actions are part of the default "browse" view styles, so I'd suggest adding `.browse` to the body tag, and maybe `.past-imports` as well to help target this view better. For example, your module could add the following styles to use automatic widths for that first column, since your zotero library strings won't be very long and don't need the default 50% width styles:

```
.browse.past-imports td:first-child, 
.browse.past-imports th:first-child {
    width: auto;
}
```
