### ISSUE TITLE
UI is different from other importers

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/ZoteroImport#8]
The CSV and Omeka 2 Importers have sub-nav options for "Import" and "Past Imports" while on Zotero Import, it's tabs on the page labelled "Import" and "Browse Imports."

Consistency of language would be good, if nothing else - for the record I prefer "Past Imports"

**Comment by patrickmj** [comment]
Yes. This is an artefact from early days when we weren't sure about the how to build the options into the UI (e.g., a bunch of tabs? sublinks in the navigation? other?). Back then, we went with trying out different options to see what made most sense. Many eyes on the different options seems in order, and any changes to make consistency happen I think are pretty straightforward.

**Comment by mebrett** [comment]
@jannellelegg @alyssafahringer feedback?

**Comment by alyssafahringer** [comment]
I agree with @mebrett - I prefer the term 'past imports.' I also prefer tabs as opposed to sublinks in the nav, mostly because having  tabs reduces the amount of 'clutter' in the nav, and it keeps all options pertaining to a module on the same screen (flipping back and forth between tabs makes more sense to me).

**Comment by jannellelegg** [comment]
I'm in agreement about naming, "past imports" is preferable. I can see it being useful to navigate directly to a page within this plugin using the nav - but currently, we already have to click twice to get to the browse/past imports page, so it's not easier having it in the nav. (example CSV Import) I think for consistency and clarity, the tabs make more sense to me.

**Comment by kimisgold** [comment]
I accidentally chimed in as a separate issue. My thoughts:

> All the other importers currently show the "Past Imports" view like so:
> 
> <img width="173" alt="screen shot 2016-11-15 at 5 01 48 pm" src="https://cloud.githubusercontent.com/assets/606764/20326082/3d2d53b8-ab55-11e6-8cf1-f43504ded925.png">
> 
> In core, we're avoiding tabbed navigation that points to separate views, especially if one tab contains a form so that the user doesn't navigate away from changes by accident.

So my argument is that it's better to be in the nav so that the user isn't surprised by an alert that they're leaving a form. Using tabs here is slower than in most other instances: here, you're navigating to a different view, whereas all other tabbed instances are single views broken up into tabs and toggled using javascript. Does this make sense, @alyssafahringer @jannellelegg?

**Comment by alyssafahringer** [comment]
Yes it does - thanks for the explanation!

**Comment by jimsafley** [comment]
Reopening until navigation links are corrected (by me).

**Comment by patrickmj** [comment]
There's a different, but tangentially related consistency issue, about redirecting after starting the import, being discussed wrt Omeka2Importer https://github.com/omeka-s-modules/Omeka2Importer/issues/84
